### ISSUE TITLE
Server Crashing 

### ISSUE THREAD

**Issue by AdamDAuria** [broccolai/tickets#105]
PureTickets v5.1.1 generated an exception while executing task 723262
java.lang.IllegalArgumentException: null

inside the console ^

at broccolai.tickets.bukkit.service.BukkitUserService.player(BukkitUserService.java:45) ~[?:?]
    at broccolai.tickets.bukkit.listeners.PlayerJoinListener.lambda$onPlayerJoin$0(PlayerJoinListener.java:38) ~[?:?]
    at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.1.jar:git-Paper-107]
    at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.17.1.jar:git-Paper-107]
    at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-107]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]

at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by broccolai** [comment]
Is this a offline server / running under geyser or another strange setup?

It's saying the players unique id is null which shouldn't be able to happen

**Comment by AdamDAuria** [comment]
runing geyser it a online server
