### ISSUE TITLE
Could not pass event TicketConstructionEvent to PureTickets v3.1.1

### ISSUE THREAD

**Issue by Fulavik** [broccolai/tickets#43]
[20:18:26 INFO]: Fulavik issued server command: /ticket create lol
[20:18:26 ERROR]: Could not pass event TicketConstructionEvent to PureTickets v3.1.1
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[Server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) ~[Server.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) ~[Server.jar:git-Spigot-db6de12-18fbb24]
        at broccolai.tickets.commands.TicketCommand.lambda$onCreate$0(TicketCommand.java:42) ~[?:?]
        at broccolai.tickets.lib.taskchain.TaskChainTasks$GenericTask.run(TaskChainTasks.java:83) ~[?:?]
        at broccolai.tickets.lib.taskchain.TaskChain$TaskHolder.run(TaskChain.java:1312) ~[?:?]
        at broccolai.tickets.lib.taskchain.TaskChain$TaskHolder.access$100(TaskChain.java:1266) ~[?:?]
        at broccolai.tickets.lib.taskchain.TaskChain.lambda$nextTask$18(TaskChain.java:1187) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_261]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_261]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_261]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_261]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]

**Comment by broccolai** [comment]
This should've been fixed with 3.1.2, if it's still persists please let me know!

**Comment by Fulavik** [comment]
Where can i download 3.1.2

**Comment by Fulavik** [comment]
> This should've been fixed with 3.1.2, if it's still persists please let me know!
Where can I download v 3.1.2

**Comment by broccolai** [comment]
Fixed in 5.0
