### ISSUE TITLE
Data too long for column 'player'

### ISSUE THREAD

**Issue by belzaaron** [broccolai/tickets#70]
Just installed, using: `storage-configuration: {type: MYSQL,` - running `git-Purpur-1053 (MC: 1.16.5)`. 
```
[22:18:31 INFO]: Prymiee issued server command: /ticket create hello
[22:18:31 WARN]: broccolai.tickets.dependencies.jdbi.v3.core.statement.UnableToExecuteStatementException: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'player' at row 1 [statement:"INSERT INTO puretickets_ticket(`player`, `position`, `status`, `claimer`)
[22:18:31 WARN]: VALUES (:player, :position, :status, :claimer)", arguments:{positional:{}, named:{claimer:null,position:world|702|68|-656,player:deda0d40-864c-4419-bd26-96f87116f08e,status:OPEN}, finder:[]}]
[22:18:31 WARN]:        at broccolai.tickets.dependencies.jdbi.v3.core.statement.SqlStatement.internalExecute(SqlStatement.java:1794)
[22:18:31 WARN]:        at broccolai.tickets.dependencies.jdbi.v3.core.result.ResultProducers.lambda$returningUpdateCount$0(ResultProducers.java:46)
[22:18:31 WARN]:        at broccolai.tickets.dependencies.jdbi.v3.core.statement.Update.execute(Update.java:60)
[22:18:31 WARN]:        at broccolai.tickets.dependencies.jdbi.v3.core.statement.Update.execute(Update.java:48)
[22:18:31 WARN]:        at broccolai.tickets.core.service.storage.DatabaseStorageService.lambda$create$0(DatabaseStorageService.java:86)
[22:18:31 WARN]:        at broccolai.tickets.dependencies.jdbi.v3.core.Jdbi.withHandle(Jdbi.java:341)
[22:18:31 WARN]:        at broccolai.tickets.core.service.storage.DatabaseStorageService.create(DatabaseStorageService.java:78)
[22:18:31 WARN]:        at broccolai.tickets.core.service.ticket.CachedTicketService.create(CachedTicketService.java:50)
[22:18:31 WARN]:        at broccolai.tickets.core.service.interaction.EventInteractionService.create(EventInteractionService.java:78)
[22:18:31 WARN]:        at broccolai.tickets.core.commands.command.TicketCommand.processCreate(TicketCommand.java:136)
[22:18:31 WARN]:        at broccolai.tickets.dependencies.commandframework.execution.AsynchronousCommandExecutionCoordinator.lambda$coordinateExecution$0(AsynchronousCommandExecutionCoordinator.java:85)
[22:18:31 WARN]:        at broccolai.tickets.dependencies.commandframework.execution.AsynchronousCommandExecutionCoordinator.lambda$coordinateExecution$2(AsynchronousCommandExecutionCoordinator.java:115)
[22:18:31 WARN]:        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
[22:18:31 WARN]:        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[22:18:31 WARN]:        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[22:18:31 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[22:18:31 WARN]:        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[22:18:31 WARN]:        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[22:18:31 WARN]: Caused by: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'player' at row 1
[22:18:31 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3931)
[22:18:31 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
[22:18:31 WARN]:        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
[22:18:31 WARN]:        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675)
[22:18:31 WARN]:        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
[22:18:31 WARN]:        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1915)
[22:18:31 WARN]:        at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1254)
[22:18:31 WARN]:        at broccolai.tickets.dependencies.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
[22:18:31 WARN]:        at broccolai.tickets.dependencies.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
[22:18:31 WARN]:        at broccolai.tickets.dependencies.jdbi.v3.core.statement.SqlLoggerUtil.wrap(SqlLoggerUtil.java:31)
[22:18:31 WARN]:        at broccolai.tickets.dependencies.jdbi.v3.core.statement.SqlStatement.internalExecute(SqlStatement.java:1786)
[22:18:31 WARN]:        ... 17 more
```

MariaDB 10.5.9 Stable. Connection string addons: `?useSSL=false&autoReconnect=true`

**Comment by broccolai** [comment]
Hi, sorry about taking so long, I'm away from home right now and my setup isn't great.

Could you try the version building [here](https://github.com/broccolai/tickets/runs/2328523315)

I was able to recreate something similar and I believe this should fix it but they might not be related.

**Comment by belzaaron** [comment]
That seemed to have fixed the issue, @broccolai - thank you for replying quickly. Is there anything else you may need from me at this time?

**Comment by broccolai** [comment]
Nope! Glad that fixed it, if an error similar to that occurs again comment it here, I think I got all instances of it though.

I'll do a release on Spigot soon, thank you!
